basic_settings:
  site_title: Michael Levy
  favicon_image:

# Setup your navigation
menu_settings:
  menu_items:
    - title: 'Info'
      url: '/info'
  menu_items2:
    - title: 'Index'
      url: '/'
